apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-search-db-pv
  labels:
    app: sqlite-api
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /kind-host-data
    type: DirectoryOrCreate
