apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: job-search-db-pvc
  namespace: job-search
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: job-search-db-pv
